version: '3.1'

services:
  application-webserver:
    env_file:
      - environment.env
    depends_on:
      - database
    build:
      context: .
    ports:
      - 9999:8001

  database:
    image: postgres:12.0-alpine
    env_file:
      - environment.env
    volumes:
      - ./docker-config-files/db_init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}

volumes:
  postgres_data:
